
# This file is used to configure your Supabase project.
# It's very minimal at the moment and uses default values.
# You can learn more here: https://supabase.io/docs/guides/hosting/overview

project_id = "jlehibsrdvnssnmfdogp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[functions]
port = 54324

[storage]
port = 54325

[auth]
port = 54326
