// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlehibsrdvnssnmfdogp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZWhpYnNyZHZuc3NubWZkb2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MDQ5NTksImV4cCI6MjA1ODI4MDk1OX0.X3c2c0D-9y95251gX7r0gzVRRt9bqkjOIvvySGNvQY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);